# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.add_index_response_data import AddIndexResponseData
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AddIndexResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: AddIndexResponseData=None):
        """
        AddIndexResponse - a model defined in Swagger

        :param message: The message of this AddIndexResponse.
        :type message: str
        :param data: The data of this AddIndexResponse.
        :type data: AddIndexResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': AddIndexResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AddIndexResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddIndexResponse of this AddIndexResponse.
        :rtype: AddIndexResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this AddIndexResponse.

        :return: The message of this AddIndexResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this AddIndexResponse.

        :param message: The message of this AddIndexResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> AddIndexResponseData:
        """
        Gets the data of this AddIndexResponse.

        :return: The data of this AddIndexResponse.
        :rtype: AddIndexResponseData
        """
        return self._data

    @data.setter
    def data(self, data: AddIndexResponseData):
        """
        Sets the data of this AddIndexResponse.

        :param data: The data of this AddIndexResponse.
        :type data: AddIndexResponseData
        """

        self._data = data

