# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.index import Index
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class GetIndexResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None, data: Index=None):
        """
        GetIndexResponse - a model defined in Swagger

        :param message: The message of this GetIndexResponse.
        :type message: str
        :param data: The data of this GetIndexResponse.
        :type data: Index
        """
        self.swagger_types = {
            'message': str,
            'data': Index
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetIndexResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetIndexResponse of this GetIndexResponse.
        :rtype: GetIndexResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this GetIndexResponse.

        :return: The message of this GetIndexResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this GetIndexResponse.

        :param message: The message of this GetIndexResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Index:
        """
        Gets the data of this GetIndexResponse.

        :return: The data of this GetIndexResponse.
        :rtype: Index
        """
        return self._data

    @data.setter
    def data(self, data: Index):
        """
        Sets the data of this GetIndexResponse.

        :param data: The data of this GetIndexResponse.
        :type data: Index
        """

        self._data = data

